name: Test Deployment

on:
  push:
  workflow_dispatch:

jobs:
  test deployment:
    name: Test Deployment
    runs-on: ubuntu-20.04
    steps:
    - name: Make Request
      id: httpTest
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://${{ secrets.AZURE_APP_NAME }}.azurewebsites.net/api/v1"
    - name: Show Response
      run: |
        echo ${{ steps.httpTest.outputs.response }}